# Generated by Django 4.0.4 on 2022-06-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_location_city_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.IntegerField(default=37.8393, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.IntegerField(default=86.27, max_length=100),
        ),
    ]
