# Generated by Django 4.0.4 on 2022-06-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_location_lat_location_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=37.8393, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=86.27, max_length=100),
        ),
    ]
