# Generated by Django 4.0.4 on 2022-06-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='img2',
            field=models.CharField(default='https://us.123rf.com/450wm/pavelstasevich/pavelstasevich1811/pavelstasevich181101028/112815904-no-image-available-icon-flat-vector-illustration.jpg?ver=6', max_length=700),
        ),
        migrations.AddField(
            model_name='location',
            name='img3',
            field=models.CharField(default='https://us.123rf.com/450wm/pavelstasevich/pavelstasevich1811/pavelstasevich181101028/112815904-no-image-available-icon-flat-vector-illustration.jpg?ver=6', max_length=700),
        ),
        migrations.AddField(
            model_name='location',
            name='img4',
            field=models.CharField(default='https://us.123rf.com/450wm/pavelstasevich/pavelstasevich1811/pavelstasevich181101028/112815904-no-image-available-icon-flat-vector-illustration.jpg?ver=6', max_length=700),
        ),
    ]
