# Generated by Django 4.0.4 on 2022-06-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_location_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='location',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='location',
            name='img4',
        ),
    ]
